### ISSUE TITLE
dataset download ？

### ISSUE THREAD

**Issue by ghost** [liuzhejun/XWbank_LipReading#1]
请问数据有链接吗？官方数据下载有权限

**Comment by liuzhejun** [comment]
抱歉，数据集的版权属于主办方，我们签订的协议是不能泄露的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Unabeviable"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 晚上9:53
收件人:&nbsp;"liuzhejun/XWbank_LipReading"<XWbank_LipReading@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[liuzhejun/XWbank_LipReading] dataset download ？ (#1)




请问数据有链接吗？官方数据下载有权限

**Comment by ghost** [comment]
谢谢





发自我的iPhone


------------------ Original ------------------
