### ISSUE TITLE
train.py运行时线程出错

### ISSUE THREAD

**Issue by mangotuanzi** [liuzhejun/XWbank_LipReading#2]
作者你好，我在尝试你的项目时，在运行初赛代码中train,py时出现线程错误，能否请教是有其他的一些配置吗？希望能解答

**Comment by liuzhejun** [comment]
具体报的什么错呢？哪行代码出错？

**Comment by mangotuanzi** [comment]
你好，非常感谢收到你的回复。
我在运行你的初赛代码中的train.py（前面两步我已经走过，数据也找到当初比赛的数据）时，出现线程错误，但是我的内存是40G，应该不会被占满，出错的截图我附在邮件中。
希望得到你的解答，再次感谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhejun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上9:20
收件人:&nbsp;"liuzhejun/XWbank_LipReading"<XWbank_LipReading@noreply.github.com&gt;;
抄送:&nbsp;"芒果大队长"<411429343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhejun/XWbank_LipReading] train.py运行时线程出错 (#2)





 
具体报的什么错呢？哪行代码出错？

**Comment by mangotuanzi** [comment]
你好，能否告知我在运行train.py时的具体步骤呢，我是不是遗漏了哪里的修改，希望收到你的解答，感谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhejun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上9:20
收件人:&nbsp;"liuzhejun/XWbank_LipReading"<XWbank_LipReading@noreply.github.com&gt;;
抄送:&nbsp;"芒果大队长"<411429343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhejun/XWbank_LipReading] train.py运行时线程出错 (#2)





 
具体报的什么错呢？哪行代码出错？

**Comment by liuzhejun** [comment]
没有看到你的截图，给出几点建议：\\
train,py中只有两处涉及到多进程，一是[处理训练数据：] \\(https://github.com/liuzhejun/XWbank_LipReading/blob/e8e1136c6526526d7c418fdfa886b4e5237e368f/%E5%88%9D%E8%B5%9B%E4%BB%A3%E7%A0%81/train.py#L78)
二是产生产生额外进程[缓存处理好的数据：] \\(https://github.com/liuzhejun/XWbank_LipReading/blob/e8e1136c6526526d7c418fdfa886b4e5237e368f/%E5%88%9D%E8%B5%9B%E4%BB%A3%E7%A0%81/train.py#L296) 

建议实时监控内存使用情况，40G有可能爆的，我当时用的256G内存。其次看磁盘大小是否足够，是不是缓存数据没空间了，K折的情况下数据集文件和缓存数据加起来快200G了。

**Comment by mangotuanzi** [comment]
你好，内存需要那么大吗？我的磁盘应该没问题，因为我是租的服务器，内存最大只有54G，这是导致出错的原因吗，因为我没有改动代码，并且这个你是在CPU上跑的吗？如果改到GPU能吗？需要改哪里呢？希望收到你的解答，感谢。并且我刚刚应该附了截图在邮件中，我向你发送了两封邮件。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhejun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上9:50
收件人:&nbsp;"liuzhejun/XWbank_LipReading"<XWbank_LipReading@noreply.github.com&gt;;
抄送:&nbsp;"芒果大队长"<411429343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhejun/XWbank_LipReading] train.py运行时线程出错 (#2)





 
没有看到你的截图，给出几点建议：\
 train,py中只有两处涉及到多进程，一是[处理训练数据：] \(https://github.com/liuzhejun/XWbank_LipReading/blob/e8e1136c6526526d7c418fdfa886b4e5237e368f/%E5%88%9D%E8%B5%9B%E4%BB%A3%E7%A0%81/train.py#L78)
 二是产生产生额外进程[缓存处理好的数据：] \(https://github.com/liuzhejun/XWbank_LipReading/blob/e8e1136c6526526d7c418fdfa886b4e5237e368f/%E5%88%9D%E8%B5%9B%E4%BB%A3%E7%A0%81/train.py#L296)
 
建议实时监控内存使用情况，40G有可能爆的，我当时用的256G内存。其次看磁盘大小是否足够，是不是缓存数据没空间了，K折的情况下数据集文件和缓存数据加起来快200G了。

**Comment by mangotuanzi** [comment]
你好，如果我用单线程，是否可以呢，那要修改哪里呢，希望收到你的解答，感谢。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhejun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上9:50
收件人:&nbsp;"liuzhejun/XWbank_LipReading"<XWbank_LipReading@noreply.github.com&gt;;
抄送:&nbsp;"芒果大队长"<411429343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhejun/XWbank_LipReading] train.py运行时线程出错 (#2)





 
没有看到你的截图，给出几点建议：\
 train,py中只有两处涉及到多进程，一是[处理训练数据：] \(https://github.com/liuzhejun/XWbank_LipReading/blob/e8e1136c6526526d7c418fdfa886b4e5237e368f/%E5%88%9D%E8%B5%9B%E4%BB%A3%E7%A0%81/train.py#L78)
 二是产生产生额外进程[缓存处理好的数据：] \(https://github.com/liuzhejun/XWbank_LipReading/blob/e8e1136c6526526d7c418fdfa886b4e5237e368f/%E5%88%9D%E8%B5%9B%E4%BB%A3%E7%A0%81/train.py#L296)
 
建议实时监控内存使用情况，40G有可能爆的，我当时用的256G内存。其次看磁盘大小是否足够，是不是缓存数据没空间了，K折的情况下数据集文件和缓存数据加起来快200G了。

**Comment by liuzhejun** [comment]
具体内存要多少我也忘了，你不能实时监控内存吗？用htop或者top命令。
数据处理是在cpu上跑的，训练是在GPU。
使用单线程的话修改我之前回复你的两处链接。
你把截图直接贴回复里可以吗，附件真的没找到

**Comment by mangotuanzi** [comment]
你好，我试过监控内存，好像是内存往显存拷数据出错了，那两行代码我要怎么修改呢？我把截图放在下面了，希望收到你的回复，感谢。
train_data = pool.map(padding_batch, iter_list)
new_process_to_save_data('cache/cache.dat', train_data, train_label, eval_data, eval_label)











------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhejun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上10:02
收件人:&nbsp;"liuzhejun/XWbank_LipReading"<XWbank_LipReading@noreply.github.com&gt;;
抄送:&nbsp;"芒果大队长"<411429343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhejun/XWbank_LipReading] train.py运行时线程出错 (#2)





 
具体内存要多少我也忘了，你不能实时监控内存吗？用htop或者top命令。
 数据处理是在cpu上跑的，训练是在GPU。
 使用单线程的话修改我之前回复你的两处链接。
 你把截图直接贴回复里可以吗，附件真的没找到

**Comment by liuzhejun** [comment]
图是被吃了吗？
加我qq978891522说吧
